FROM ubuntu:22.10

ARG user
ARG uid

RUN apt-get update && apt-get install -y \
    php8.1 \
    apache2

# RUN apt-get update && apt-get install -y \
#     git \
#     curl \
#     libpng-dev \
#     libonig-dev \
#     libxml2-dev \
#     zip \
#     unzip\
#     libfreetype-dev \
# 		libjpeg62-turbo-dev \
# 		libpng-dev \
# 	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
# 	&& docker-php-ext-install -j$(nproc) gd pdo pdo_mysql mbstring exif pcntl bcmath

# RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# RUN pecl install xdebug \
#     && docker-php-ext-enable xdebug

# Copy apache vhost file to proxy php requests to php-fpm container
COPY apache2.conf /etc/apache2/apache2.conf

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

RUN apachectl restart

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

WORKDIR /var/www

USER $user